### ISSUE TITLE
[Suggestion] Extract only from output slot

### ISSUE THREAD

**Issue by AxelTheModder** [userTravis/Chambers#12] opened 2021-05-31 02:57 UTC
Extracting from every slot, even the input slots, would break automation imo

**Comment by userTravis** [comment] 2021-05-31 03:11
Duplicate of #8 
Currently the solution in game is to use filters/whitelists to only pull in the completed output items(or blacklist input items).

**Closed as completed by userTravis** 2021-05-31 03:11 UTC
